name: flutter_advanced_networkimage
description: An advanced image provider for flutter.
version: 0.3.2
author: "fuyumi <fnatic.roach@gmail.com>"
homepage: https://github.com/mchome/flutter_advanced_networkimage

dependencies:
  flutter:
    sdk: flutter
  http: "^0.11.3"
  path_provider: "^0.4.1"
  quiver: ">=2.0.0 <3.0.0"
  path: "^1.6.0"
  crypto: "^2.0.5"

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"