name: flutter_advanced_networkimage
description: An advanced image provider provides caching and retrying for flutter app. Now with zoomable widget and transition to image widget
version: 0.4.7
author: "fuyumi <fnatic.roach@gmail.com>"
homepage: https://github.com/mchome/flutter_advanced_networkimage

dependencies:
  flutter:
    sdk: flutter
  http: "^0.12.0"
  path_provider: "^0.5.0"
  path: "^1.6.0"
  flutter_svg: "^0.10.2"

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: "^1.3.0"

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.1.7 <2.0.0"
